# -*- coding: utf-8 -*-
"""AIPP_ASSIGN3_BILL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17-tXfWrEubJnHUmpZul1mkUuT_c89gt2
"""

''' Objective:
Build a Python program for TGNPDCL (Telangana Northern Power Distribution Company Limited) to generate an electricity bill based on
energy consumption and type of customer.
Requirements:
1. Read inputs: previous units (PU), current units (CU), and customer type (Domestic, Commercial, or Industrial)
2. Calculate:
  - EC (Energy Charges)
  - FC (Fixed Charges)
  - CC (Customer Charges)
  - ED (Electricity Duty, 5% of EC)
  - Total Bill = EC + FC + CC + ED
3. Print a clear bill summary with all details.
4. Use simple logic for rates:
5. Use AI assistance to generate the full code structure, input handling, and output formatting.
Task:
 Generate the complete Python code for this electricity bill calculator.
'''

"""### Electricity Bill Calculator for TGNPDCL

This program calculates the electricity bill based on energy consumption and customer type (Domestic, Commercial, or Industrial). It includes Energy Charges (EC), Fixed Charges (FC), Customer Charges (CC), and Electricity Duty (ED).
"""

# Define rates for different customer types and consumption slabs

# Domestic Rates (per unit)
DOMESTIC_RATES = [
    (50, 1.50),   # First 50 units
    (100, 3.00),  # Next 50 units (51-100)
    (200, 4.50),  # Next 100 units (101-200)
    (float('inf'), 6.00) # Above 200 units
]
DOMESTIC_FC = 50  # Fixed Charges
DOMESTIC_CC = 20  # Customer Charges

# Commercial Rates (per unit)
COMMERCIAL_RATES = [
    (100, 7.00),  # First 100 units
    (300, 9.00),  # Next 200 units (101-300)
    (float('inf'), 11.00) # Above 300 units
]
COMMERCIAL_FC = 200 # Fixed Charges
COMMERCIAL_CC = 50  # Customer Charges

# Industrial Rates (per unit)
INDUSTRIAL_RATES = [
    (500, 8.00),  # First 500 units
    (1000, 10.00), # Next 500 units (501-1000)
    (float('inf'), 12.00) # Above 1000 units
]
INDUSTRIAL_FC = 500 # Fixed Charges
INDUSTRIAL_CC = 100 # Customer Charges

ELECTRICITY_DUTY_RATE = 0.05 # 5% of EC

def get_customer_inputs():
    user_name = input("Enter Customer Name: ").strip()
    while not user_name:
        print("Customer Name cannot be empty. Please enter a name.")
        user_name = input("Enter Customer Name: ").strip()

    while True:
        try:
            prev_units = float(input("Enter Previous Units (PU): "))
            if prev_units < 0:
                print("Previous Units cannot be negative. Please try again.")
                continue
            break
        except ValueError:
            print("Invalid input for Previous Units. Please enter a number.")

    while True:
        try:
            curr_units = float(input("Enter Current Units (CU): "))
            if curr_units < prev_units:
                print("Current Units cannot be less than Previous Units. Please try again.")
                continue
            break
        except ValueError:
            print("Invalid input for Current Units. Please enter a number.")

    while True:
        customer_type = input("Enter Customer Type (Domestic, Commercial, or Industrial): ").strip().lower()
        if customer_type in ['domestic', 'commercial', 'industrial']:
            break
        else:
            print("Invalid Customer Type. Please choose from 'Domestic', 'Commercial', or 'Industrial'.")

    return user_name, prev_units, curr_units, customer_type

def calculate_energy_charges(units_consumed, rates):
    ec = 0
    remaining_units = units_consumed

    # Sort rates by slab limit to ensure correct processing
    sorted_rates = sorted(rates, key=lambda x: x[0])

    for slab_limit, rate_per_unit in sorted_rates:
        if remaining_units <= 0:
            break

        if slab_limit == float('inf'): # Last slab handles all remaining units
            ec += remaining_units * rate_per_unit
            remaining_units = 0
        elif remaining_units <= slab_limit: # Current slab can cover remaining units
            ec += remaining_units * rate_per_unit
            remaining_units = 0
        else: # Current slab is fully consumed
            slab_units = slab_limit if len(rates) > 1 and rates.index((slab_limit, rate_per_unit)) < len(rates) -1 else remaining_units # This logic needs adjustment for cumulative slabs

            # Corrected slab calculation for cumulative units
            if rates.index((slab_limit, rate_per_unit)) == 0:
                units_in_slab = min(units_consumed, slab_limit)
                ec += units_in_slab * rate_per_unit
                remaining_units -= units_in_slab
            else:
                prev_slab_limit = rates[rates.index((slab_limit, rate_per_unit)) - 1][0]
                slab_capacity = slab_limit - prev_slab_limit
                units_in_slab = min(remaining_units, slab_capacity)
                ec += units_in_slab * rate_per_unit
                remaining_units -= units_in_slab

    return ec

def calculate_bill():
    user_name, prev_units, curr_units, customer_type = get_customer_inputs()
    units_consumed = curr_units - prev_units

    ec = 0
    fc = 0
    cc = 0

    if customer_type == 'domestic':
        ec = calculate_energy_charges(units_consumed, DOMESTIC_RATES)
        fc = DOMESTIC_FC
        cc = DOMESTIC_CC
    elif customer_type == 'commercial':
        ec = calculate_energy_charges(units_consumed, COMMERCIAL_RATES)
        fc = COMMERCIAL_FC
        cc = COMMERCIAL_CC
    elif customer_type == 'industrial':
        ec = calculate_energy_charges(units_consumed, INDUSTRIAL_RATES)
        fc = INDUSTRIAL_FC
        cc = INDUSTRIAL_CC
    else:
        print("Error: Unknown customer type.")
        return

    ed = ec * ELECTRICITY_DUTY_RATE
    total_bill = ec + fc + cc + ed

    return {
        'Customer Name': user_name,
        'Previous Units': prev_units,
        'Current Units': curr_units,
        'Units Consumed': units_consumed,
        'Customer Type': customer_type.capitalize(),
        'Energy Charges (EC)': ec,
        'Fixed Charges (FC)': fc,
        'Customer Charges (CC)': cc,
        'Electricity Duty (ED)': ed,
        'Total Bill Amount': total_bill
    }

def print_bill_summary(bill_details):
    if bill_details:
        print("\n--- Electricity Bill Summary ---")
        for key, value in bill_details.items():
            if isinstance(value, (int, float)):
                print(f"{key:<25}: {value:,.2f}")
            else:
                print(f"{key:<25}: {value}")
        print("---------------------------------")

# Run the calculator
bill = calculate_bill()
print_bill_summary(bill)