"""
•	Generate test cases using AI for is_sentence_palindrome(sentence). Ignore case, punctuation, and spaces
Requirement
•	Ask AI to create test cases for is_sentence_palindrome(sentence)
(ignores case, spaces, and punctuation).
•	Example:
"A man a plan a canal Panama" → True
Expected Output#3
generate a python code for the function is_sentence_palindrome(sentence) and pass the test cases generated by the AI(include test cases like Ignore case, punctuation, and spaces).
•	Function returns True/False for cleaned sentences
•	Implement the function to pass AI-generated tests.

PROMPT:
# Python: Generate test cases and implementation for is_sentence_palindrome(sentence).
# Ignore case, punctuation, and spaces.
# Include test cases like "A man a plan a canal Panama" → True.
# Then, implement the function and add code to take user input for the sentence and print the result.   
"""
def is_sentence_palindrome(sentence):
    sentence = sentence.lower()
    sentence = sentence.replace(" ", "")
    sentence = sentence.replace(".", "")
    sentence = sentence.replace(",", "")
    sentence = sentence.replace("!", "")
    sentence = sentence.replace("?", "")
    return sentence == sentence[::-1]

sentence = input("Enter a sentence: ")
print(is_sentence_palindrome(sentence))             

