"""
•	Let AI fix it Prompt AI to generate test cases for a ShoppingCart class (add_item, remove_item, total_cost).

Methods:
Add_item(name,orice)
Remove_item(name)
Total_cost()

Expected Output#4
generate a python code for the ShoppingCart class and pass the test cases generated by the AI(include test cases for add_item, remove_item, and total_cost).
Read the input from the user for the name and price and print the result like total cost, items, remove item, and total cost.
ask the user to add more items or remove items or exit the program.

    Example:
    Enter the name of the item: Apple
    Enter the price of the item: 1.00
    Total cost: 1.00
    Items: {'Apple': 1.00}
    Remove item: Apple
    Total cost: 0.00
    Items: {}
    Add more items or remove items or exit the program: exit  #use while loop to add more items or remove items or exit the program.    
"""
# ============================================
# 🛍️ SHOPPING CART SIMULATION SYSTEM
# ============================================

class ShoppingCart:
    def __init__(self, inventory):
        # Available items in the store
        self.inventory = inventory
        # Customer's cart
        self.cart = {}

    def display_inventory(self):
        """Display available items in the store."""
        print("\n🛒 Available Items in Inventory:")
        for name, price in self.inventory.items():
            print(f" - {name}: ₹{price:.2f}")

    def display_cart(self):
        """Display items in the user's cart."""
        if not self.cart:
            print("\n🛍️ Your cart is empty.")
        else:
            print("\n🛍️ Items in your Cart:")
            for name, price in self.cart.items():
                print(f" - {name}: ₹{price:.2f}")
            print(f"\n💰 Total Bill: ₹{self.total_cost():.2f}")

    def add_item(self, name):
        """Add an item to the cart if it exists in inventory."""
        if name in self.inventory:
            self.cart[name] = self.inventory[name]
            print(f"✅ {name} added to your cart for ₹{self.inventory[name]:.2f}")
        else:
            print(f"⚠️ {name} not found in inventory!")

    def remove_item(self, name):
        """Remove an item from the cart."""
        if name in self.cart:
            del self.cart[name]
            print(f"🗑️ {name} removed from your cart.")
        else:
            print(f"⚠️ {name} not found in your cart!")

    def total_cost(self):
        """Return the total cost of items in the cart."""
        return sum(self.cart.values())


# ============================================
# 🧠 AI-GENERATED TEST CASES
# ============================================

print("===== Running AI-Generated Test Cases =====")

# Create a sample inventory
inventory = {"Apple": 50.0, "Banana": 20.0, "Mango": 60.0, "Milk": 40.0}
cart = ShoppingCart(inventory)

# Test Case 1: Add items
cart.add_item("Apple")   # Expected: Added successfully
cart.add_item("Banana")  # Expected: Added successfully

# Test Case 2: Try adding non-existent item
cart.add_item("Chocolate")  # Expected: Not found in inventory

# Test Case 3: Remove item
cart.remove_item("Apple")   # Expected: Removed successfully

# Test Case 4: Remove non-existent item
cart.remove_item("Orange")  # Expected: Not found in cart

# Test Case 5: Total cost
print(f"Final Total Cost: ₹{cart.total_cost():.2f}")  # Expected: ₹20.00

print("===========================================\n")


# ============================================
# 💬 INTERACTIVE CUSTOMER INTERFACE
# ============================================

def main():
    inventory = {
        "Apple": 50.0,
        "Banana": 20.0,
        "Mango": 60.0,
        "Milk": 40.0,
        "Bread": 35.0,
        "Eggs": 70.0
    }

    cart = ShoppingCart(inventory)

    print("🌟 Welcome to SmartMart! 🌟")
    while True:
        print("\nChoose an option:")
        print("1️⃣ View Inventory")
        print("2️⃣ View Cart")
        print("3️⃣ Add Item to Cart")
        print("4️⃣ Remove Item from Cart")
        print("5️⃣ View Total Bill")
        print("6️⃣ Exit")

        choice = input("Enter your choice (1-6): ").strip()

        if choice == "1":
            cart.display_inventory()

        elif choice == "2":
            cart.display_cart()

        elif choice == "3":
            cart.display_inventory()
            name = input("Enter the item name to add: ").strip()
            cart.add_item(name)

        elif choice == "4":
            cart.display_cart()
            name = input("Enter the item name to remove: ").strip()
            cart.remove_item(name)

        elif choice == "5":
            print(f"\n💰 Your total bill is: ₹{cart.total_cost():.2f}")

        elif choice == "6":
            print("\n🧾 Final Cart Summary:")
            cart.display_cart()
            print("Thank you for shopping with SmartMart! 🛍️")
            break

        else:
            print("⚠️ Invalid option. Please enter a number from 1 to 6.")


if __name__ == "__main__":
    main()
